/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bydan.ingles;

import java.sql.SQLException;

import com.bydan.framework.ingles.business.logic.Pagination;
import com.bydan.ingles.general.area.business.entity.Area;
import com.bydan.ingles.general.area.business.logic.Area_logic;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        try {
			Area_logic area_logic = new Area_logic();
			
			area_logic.getTodosWithConnection("", new Pagination());
			
			for(Area area : area_logic.getAreas()) {
				System.out.println(area);
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
    }
}
