package com.bydan.framework.ingles.presentation.swing.jinternalframes;

public enum TipoProceso {
	CONCEPTO,CONCEPTO_DETALLE,DICCIONARIO,EXPRESION,EXPRESION_DETALLE,GRAMMAR,GRAMMAR_DETALLE,NUMERO_GENERAL,PAIS_GENERAL,VERBO_COMPUESTO,VERBO_IRREGULAR,VOCABULARIO
}
